### ISSUE TITLE
Bot not running; DB profile for "None"

### ISSUE THREAD

**Issue by remyx11** [breuerfelix/instapy-gui#116]
hi guys,

I've installed everything like the tutorials (im on a Mac). Got the bot started, and via instapy.io I am able to get the bot running. However it gives an error straight away;

WARNING [2020-08-13 16:10:34] Heeh! Error occurred while getting a DB profile for 'None': b'NOT NULL constraint failed: profiles.name' (this is in instapy.io)

and Terminal gives this;

Custom workspace set: "/Users/remy/Downloads/instaspy/assets/InstaPy" :]
InstaPy Version: 0.6.10
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/remy/Downloads/instaspy/assets/InstaPy"
WARNING [2020-08-13 16:10:34] [None]  Heeh! Error occurred while getting a DB profile for 'None':
	b'NOT NULL constraint failed: profiles.name'
Traceback (most recent call last):
  File "bot.py", line 125, in <module>
    session = InstaPy(**instapy_args)
  File "/Users/remy/Downloads/instaspy/env/lib/python3.8/site-packages/instapy/instapy.py", line 309, in __init__
    get_database(make=True)  # IMPORTANT: think twice before relocating
  File "/Users/remy/Downloads/instaspy/env/lib/python3.8/site-packages/instapy/database_engine.py", line 66, in get_database
    get_profile(name, address, logger) if profile_id is None or make else profile_id
  File "/Users/remy/Downloads/instaspy/env/lib/python3.8/site-packages/instapy/database_engine.py", line 167, in get_profile
    profile = dict(profile)
TypeError: 'NoneType' object is not iterable

I've found some similar issue on InstaPy GitHub, but im not understanding that solution.

Can someone help me?

**Comment by breuerfelix** [comment]
can you link the issue on the instapy github here ? cause this seems to be an issue with instapy

**Comment by remyx11** [comment]
its this one; https://github.com/timgrossmann/InstaPy/issues/2588 looks about the same issue

**Comment by ErezAmihud** [comment]
For everyone seeing it next, when this error was thrown for me - it was because the setting file had missing username/password
