### ISSUE TITLE
RuntimeError: Error, unable to determine correct filename for 64bit linux : Docker Image

### ISSUE THREAD

**Issue by Vikaskumargd** [breuerfelix/instapy-gui#133]
`Traceback (most recent call last):

Custom workspace set: "/usr/instapy/assets/InstaPy" :]

InstaPy Version: 0.6.12

File "bot.py", line 125, in <module>

._. ._. ._. ._. ._. ._. ._. ._. ._. ._.

session = InstaPy(**instapy_args)

Workspace in use: "/usr/instapy/assets/InstaPy"

File "/usr/local/lib/python3.7/site-packages/instapy/instapy.py", line 335, in __init__

geckodriver_log_level,

File "/usr/local/lib/python3.7/site-packages/instapy/browser.py", line 131, in set_selenium_local_session

driver_path = geckodriver_path or get_geckodriver()

File "/usr/local/lib/python3.7/site-packages/instapy/browser.py", line 38, in get_geckodriver

sym_path = gdd.download_and_install()[1]

File "/usr/local/lib/python3.7/site-packages/webdriverdownloader/webdriverdownloader.py", line 177, in download_and_install

show_progress_bar=show_progress_bar)

File "/usr/local/lib/python3.7/site-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download

download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)

File "/usr/local/lib/python3.7/site-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url

raise RuntimeError(info_message)

RuntimeError: Error, unable to determine correct filename for 64bit linux`

**Comment by hbakhtiyor** [comment]
same issue

i run the docker in win10

![image](https://user-images.githubusercontent.com/3434496/109825072-44055380-7c5b-11eb-93a1-412a9ae37fef.png)

**Comment by hbakhtiyor** [comment]
> 
> 
> Check here [timgrossmann/InstaPy#5778](https://github.com/timgrossmann/InstaPy/issues/5778)
> I solved with: sudo apt install firefox-geckodriver

do you mean inside of docker container?
