### ISSUE TITLE
Got it installed on Raspberry Pi but it doesn't run. Wrong Chromedriver?

### ISSUE THREAD

**Issue by GaWr26** [breuerfelix/instapy-gui#52]
First of all what a great update!
but I do get these errors:

```
INFO [2019-07-11 17:23:59] [xxx]  Using built in instapy-chromedriver executable (version 2.46)
Traceback (most recent call last):
  File "bot.py", line 121, in <module>
    session = InstaPy(**instapy_args)
  File "/home/pi/InstaPyGUI/env/lib/python3.7/site-packages/instapy/instapy.py", line 327, in __init__
    self.set_selenium_local_session()
  File "/home/pi/InstaPyGUI/env/lib/python3.7/site-packages/instapy/instapy.py", line 388, in set_selenium_local_session
    self.browser_binary_path)
  File "/home/pi/InstaPyGUI/env/lib/python3.7/site-packages/instapy/browser.py", line 147, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/pi/InstaPyGUI/env/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/pi/InstaPyGUI/env/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/local/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/InstaPyGUI/env/lib/python3.7/site-packages/instapy_chromedriver/chromedriver_linux64'
```

**Comment by breuerfelix** [comment]
thanks alot :)

you have to make some adjustments for raspberry pi (I will mention that in the readme now :))

activate your virtual environment and execute these commands:

```
python3 -m pip uninstall instapy-chromedriver
python3 -m pip install --user instapy-chromedriver==2.36.post0
```

that should be it :)

**Comment by GaWr26** [comment]
Thanks Felix, I tried your approach with no luck.
Did it as described here: https://github.com/timgrossmann/InstaPy/issues/3907#issuecomment-460891667
in /InstaPyGUI/assets/InstaPy/assets and now it works like a charm!

Thanks again for the great work!

**Comment by breuerfelix** [comment]
thanks alot, I also put this into the readme!! :)

glad that it works :)
