### ISSUE TITLE
Error win 10 Instalacion limpia

### ISSUE THREAD

**Issue by streetloves** [breuerfelix/instapy-gui#95]
Hola, tengo este error en una instalación limpia: 

goto instapy.io and take off!
received message: {"handler":"status"}
received message: {"handler":"start","namespace":"gary","setting":"configuracion-basica"}
instapy process started
received message: {"handler":"status"}
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Custom workspace set: "C:/WINDOWS/system32/assets/InstaPy" :]
InstaPy Version: 0.6.7
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/WINDOWS/system32/assets/InstaPy"
Error, unable to determine correct filename for Nonebit win
Traceback (most recent call last):
  File "bot.py", line 125, in <module>
    session = InstaPy(**instapy_args)
  File "C:\WINDOWS\system32\env\lib\site-packages\instapy\instapy.py", line 309, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\WINDOWS\system32\env\lib\site-packages\instapy\browser.py", line 110, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "C:\WINDOWS\system32\env\lib\site-packages\instapy\browser.py", line 36, in get_geckodriver
    bin_path, sym_path = gdd.download_and_install()
  File "C:\WINDOWS\system32\env\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
  File "C:\WINDOWS\system32\env\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "C:\WINDOWS\system32\env\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for Nonebit win

**Comment by breuerfelix** [comment]
this is an error with instapy itself. instapy is not able to determine your current system. is this a 32 or 64 bit windows ?

**Comment by streetloves** [comment]
hi, win 10 64 bits, It's weird because I've done the installation on two different PCs and I get the same error on both

**Comment by mariomolla** [comment]
Hola, sabes ya como se soluciona?

**Comment by streetloves** [comment]
> Hola, sabes ya como se soluciona?

Aun no, mañana voy a probar colocando la version el win.

**Comment by breuerfelix** [comment]
you could download the geckodriver yourself and provide instapy with the path of this binary :)

are you a little familiar with python ?
